# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CIMR L2 SIC, SIED, and SIC1H ATBD v2
author: Thomas Lavergne, Norwegian Meteorological Institute
logo: book/logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'cache'
  timeout: -1

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: sea_ice_concentration_atbd.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - book/biblio.bib

# Format the citation style
sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false


# Information about where the book exists on the web
repository:
  url: https://github.com/CIMR-Algos/SeaIceConcentration_ATBD_v2  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  announcement: "This ATBD was developed in the CIMR DEVALGO project. It is being further developed in the <a href=\"https://github.com/CIMR-L2PAD\"style='color: #87CEEB;'>CIMR L2PAD</a> project."
  use_issues_button: false
  use_repository_button: true
  extra_footer: |
    <p>
    This ATBD was developed in the context of the ESA-funded CIMR DEVALGO study (2022-2024) (contract 4000137493).
    <br>
    ESA is not responsible in any way for the content of this document.
    </p>
